### PR TITLE
feat(factory): add factory pattern

### PR DESCRIPTION
**Pull request by ayazhafiz**

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@luke-bhan `docs/*` are generated files and can be ignored. Of substance are all other files.

**Comment by ayazhafiz** [comment]
> In the c++ file, you are specifying the animal destructor to be default. Then in the derived classes terrier and toucan, you are again setting their destructor to be default. Since the animal destructor is already default, why do you need to set it again because doesn't it just inherit the destructor. This may be a style thing.

Despite seeming to be the same, the dtors are actually different. `default` is a signal to the compiler to inline whatever destructor for the class it would have made had I not specified a destructor at all. But I do have to specify a dtor so that destruction of the virtual class chain happens correctly, so I use `default` to say "use the normal destructor for this class instance".

**Comment by luke-bhan** [comment]
You finished merging right?

**Comment by ayazhafiz** [comment]
Nope!

**Comment by ayazhafiz** [comment]
Can you mark approval @luke-bhan?

**Pull request merged**
